- name: Provision Mautic stack
  hosts: web
  become: true
  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/secrets.vault.yml
  strategy: free
  roles:
    - common
    - mariadb
    - nginx
    - php
    - redis
    - mautic
