name: Deploy
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  provision:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Ansible
        run: pip install ansible
      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - name: Write vault password
        run: printf '%s' '${{ secrets.ANSIBLE_VAULT_PASSWORD }}' > .vaultpass
      - name: Ansible ping
        working-directory: ansible
        run: ansible -i inventories/production/hosts.ini web -m ping
      - name: Run site playbook
        working-directory: ansible
        env:
          ANSIBLE_CONFIG: ${{ github.workspace }}/ansible/ansible.cfg
        run: |
          ansible-playbook -i inventories/production/hosts.ini playbooks/site.yml \
            --vault-password-file ../.vaultpass \
            -e domain='${{ secrets.DOMAIN }}' -e letsencrypt_email='${{ secrets.EMAIL }}'

